const styles = {
  container: {
    maxWidth: '900px',
    margin: '0 auto',
    padding: '0.3rem',
  },
  title: {
    fontSize: '1.8rem',
    marginBottom: '1.5rem',
    textAlign: 'center',
    color: '#333',
  },
  loading: {
    textAlign: 'center',
    margin: '3rem 0',
    fontSize: '1.2rem',
    color: '#666',
  },
  error: {
    textAlign: 'center',
    margin: '3rem 0',
    fontSize: '1.2rem',
    color: '#e74c3c',
  },
  searchContainer: {
    marginBottom: '2rem',
  },
  searchInput: {
    width: '100%',
    padding: '0.75rem',
    border: '1px solid #e0e0e0',
    borderRadius: '4px',
    fontSize: '1rem',
  },
  noQuizzes: {
    textAlign: 'center',
    margin: '3rem 0',
    fontSize: '1.2rem',
    color: '#666',
  },
  quizList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '1.5rem',
    marginBottom: '2rem',
  },
  quizCard: {
    backgroundColor: '#f9f9f9',
    borderRadius: '8px',
    padding: '1.5rem',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    cursor: 'pointer',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    position: 'relative',
    willChange: 'transform',
  },
  quizCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '0.75rem',
  },
  quizTopicTitle: {
    fontSize: '1.3rem',
    color: '#2c3e50',
    margin: 0,
    flex: 1,
  },
  quizInfo: {
    fontSize: '0.9rem',
    color: '#666',
  },
  quizDetailHeader: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '2rem',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  backButton: {
    backgroundColor: '#7f8c8d',
    color: 'white',
    border: 'none',
    padding: '0.8rem 1.5rem',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
  },
  quizTitle: {
    fontSize: '1.6rem',
    margin: '0',
    color: '#2c3e50',
    flex: '1',
    textAlign: 'center',
  },
  quizMeta: {
    display: 'flex',
    alignItems: 'center',
  },
  quizDate: {
    fontSize: '0.9rem',
    color: '#7f8c8d',
    margin: 0,
  },
  questionsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
    marginBottom: '2rem',
  },
  questionCard: {
    backgroundColor: '#fff',
    borderRadius: '8px',
    padding: '1.5rem',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  questionNumber: {
    fontSize: '1.2rem',
    marginBottom: '0.75rem',
    color: '#3498db',
  },
  questionText: {
    fontSize: '1.1rem',
    marginBottom: '1rem',
    lineHeight: '1.6',
  },
  toggleAnswerButton: {
    backgroundColor: '#3498db',
    color: 'white',
    border: 'none',
    padding: '0.6rem 1.2rem',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    transition: 'all 0.3s ease',
  },
  activeToggleButton: {
    backgroundColor: '#f5f5f5',
    color: '#333',
    border: 'none',
    boxShadow: 'inset 3px 0 0 #3498db',
  },
  answerContainer: {
    marginTop: '1rem',
    padding: '1rem',
    backgroundColor: '#f5f9fc',
    borderRadius: '4px',
    borderLeft: '4px solid #3498db',
  },
  answerText: {
    fontSize: '1rem',
    lineHeight: '1.6',
  },
  mathContainer: {
    overflowX: 'auto',
    padding: '5px 0',
  },
  controlsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '2rem',
  },
  filterContainer: {
    display: 'flex',
    gap: '10px',
  },
  filterButton: {
    padding: '8px 12px',
    backgroundColor: '#f5f5f5',
    border: '1px solid #e0e0e0',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  reviewStatus: {
    fontSize: '0.9rem',
    color: '#555',
    marginTop: '4px',
  },
  reviewLabel: {
    fontWeight: '600',
    marginRight: '6px',
  },
  reviewInfo: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: '10px',
    fontSize: '0.9rem',
  },
  nextReviewLabel: {
    color: '#666',
    marginRight: '6px',
  },
  nextReviewDate: {
    fontWeight: '600',
    color: '#2196F3',
  },
  completedReview: {
    color: '#4CAF50',
  },
  todayReview: {
    color: '#2196F3',
  },
  overdueReview: {
    color: '#f44336',
  },
  futureReview: {
    color: '#9e9e9e',
  },
  reviewActions: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: '25px',
    marginBottom: '20px',
  },
  completeReviewButton: {
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '4px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  disabledReviewButton: {
    backgroundColor: '#e0e0e0',
    color: '#9e9e9e',
    cursor: 'not-allowed',
  },
  nextReviewNote: {
    textAlign: 'center',
    color: '#666',
    fontSize: '0.9rem',
    marginTop: '10px',
  },
  deleteButton: {
    backgroundColor: '#ffffff',
    color: '#666',
    border: '1px solid #e0e0e0',
    borderRadius: '50%',
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: '0',
    marginLeft: '8px',
    transition: 'all 0.2s ease',
    ':hover': {
      backgroundColor: '#f44336',
      color: 'white',
      border: '1px solid #f44336',
    }
  },
  deleteIcon: {
    fontSize: '16px',
    lineHeight: 1,
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    backdropFilter: "blur(3px)",
  },
  dialog: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "30px",
    width: "90%",
    maxWidth: "400px",
    boxShadow: "0 15px 35px rgba(0,0,0,0.2)",
  },
  dialogTitle: {
    margin: "0 0 20px 0",
    fontSize: "22px",
    color: "#333",
    textAlign: "center",
    fontWeight: "600",
  },
  dialogText: {
    fontSize: "15px",
    color: "#555",
    textAlign: "center",
    marginBottom: "30px",
    fontWeight: "500",
  },
  dialogButtons: {
    display: "flex",
    justifyContent: "center",
    gap: "15px",
  },
  cancelButton: {
    padding: "12px 24px",
    backgroundColor: "#F5F5F5",
    color: "#333",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    flex: "1",
  },
  confirmButton: {
    padding: "12px 24px",
    backgroundColor: "#f44336",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 10px rgba(244, 67, 54, 0.3)",
    flex: "1",
  }
};

export default styles; 