const styles = {
  container: {
    display: "flex", 
    padding: "20px",
    paddingLeft: "60px",
    paddingRight: "60px",
  },
  containerMobile: {
    display: "flex",
    flexDirection: "column",
  },
  // 左側パネル（学習管理）
  leftPanel: {
    width: "280px",
    position: "fixed",
    top: "100px", 
    left: "60px",
    height: "auto",
    maxHeight: "calc(100vh - 180px)",
    overflowY: "hidden",
    backgroundColor: "#fff",
    borderRadius: "20px",
    boxShadow: "0 5px 15px rgba(0,0,0,0.03)",
    border: "1px solid rgba(0, 0, 0, 0.04)",
  },
  leftPanelMobile: {
    position: "static",
    width: "100%",
    maxHeight: "none",
    left: "auto",
    backgroundColor: "#fff",
    borderRadius: "20px",
    boxShadow: "0 5px 15px rgba(0,0,0,0.03)",
    border: "1px solid rgba(0, 0, 0, 0.04)",
  },
  studyInfoCard: {
    backgroundColor: "white",
    borderRadius: "16px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.08)",
    padding: "20px",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    maxHeight: "calc(100vh - 220px)",
    overflowY: "hidden",
  },
  statusIndicator: {
    display: "flex",
    alignItems: "center",
    marginBottom: "16px",
  },
  statusDot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    marginRight: "10px",
    transition: "all 0.3s ease",
  },
  statusText: {
    fontSize: "14px",
    fontWeight: "500",
    color: "#666",
    letterSpacing: "0.5px",
  },
  topicSection: {
    position: "relative",
    background: "rgba(240, 248, 255, 0.4)",
    borderRadius: "10px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.02)",
    maxHeight: "120px",
    overflowY: "auto",
  },
  topicTitle: {
    fontSize: "18px",
    fontWeight: "700",
    color: "#333",
    lineHeight: "1.3",
    position: "relative",
    wordBreak: "break-word",
  },
  motivationTag: {
    display: "block",
    fontSize: "14px",
    fontWeight: "600",
    textAlign: "left",
    marginBottom: "10px",
  },
  timerContainer: {
    textAlign: "center",
    marginTop: "10px",
    marginBottom: "25px",
    padding: "0",
    display: "flex",
    justifyContent: "center",
    flexShrink: 0,
  },
  timerContainerMobile: {
    textAlign: "center",
    marginTop: "10px",
    marginBottom: "10px",
    padding: "0",
    display: "flex",
    justifyContent: "center",
    flexShrink: 0,
    minHeight: "100px",
  },
  timerCircle: {
    width: "180px",
    height: "180px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #f8fcff 0%, #f0f8f0 100%)",
    border: "2px solid rgba(33, 150, 243, 0.2)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: "0 8px 25px rgba(0, 0, 0, 0.08), inset 0 2px 10px rgba(255, 255, 255, 0.8)",
    position: "relative",
    transition: "all 0.3s ease",
  },
  timerDigital: {
    padding: "15px 25px",
    borderRadius: "10px",
    background: "transparent",
    border: "none",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: "none",
    transition: "all 0.3s ease",
    width: "200px",
    margin: "0 auto",
  },
  timerValue: {
    fontSize: "28px",
    fontWeight: "600",
    background: "linear-gradient(135deg, #2196F3 10%, #4CAF50 90%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    fontFamily: "'Roboto Mono', monospace",
    letterSpacing: "1px",
    marginBottom: "6px",
  },
  timerPaused: {
    background: "rgba(255, 165, 0, 0.1)",
    boxShadow: "0 8px 25px rgba(255, 165, 0, 0.15), inset 0 2px 10px rgba(255, 255, 255, 0.8)",
    border: "2px solid rgba(255, 165, 0, 0.3)",
  },
  pausedIndicator: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#FF8C00",
    marginTop: "5px",
    padding: "3px 8px",
    borderRadius: "4px",
    background: "rgba(255, 165, 0, 0.1)",
    display: "inline-block",
    textAlign: "center",
    width: "fit-content",
  },
  timerValueMobile: {
    fontSize: "27px",
    fontWeight: "700",
    background: "linear-gradient(135deg, #2196F3 10%, #4CAF50 90%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    fontFamily: "'Roboto Mono', monospace",
    letterSpacing: "1px",
  },
  controlsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    marginTop: "auto",
    marginBottom: "15px",
    flexShrink: 0,
  },
  controlsContainerMobile: {
    display: "flex",
    flexDirection: "row",
    gap: "10px",
    marginTop: "auto",
    flexShrink: 0,
  },
  
  // 右側パネル（AIチャット用）
  rightPanel: {
    flex: 1,
    marginLeft: "300px",
    minHeight: "calc(100vh - 180px)",
    marginTop: "-65px",
  },
  rightPanelMobile: {
    flex: 1,
    marginLeft: "0",
    minHeight: "auto",
    marginTop: "0",
  },
  
  // モーダルダイアログ
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    backdropFilter: "blur(3px)",
  },
  dialog: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "30px",
    width: "calc(90% + 20px)",
    maxWidth: "420px",
    boxShadow: "0 15px 35px rgba(0,0,0,0.2)",
  },
  dialogTitle: {
    margin: "0 0 20px 0",
    fontSize: "22px",
    color: "#333",
    textAlign: "center",
    fontWeight: "600",
  },
  dialogText: {
    fontSize: "15px",
    color: "#555",
    textAlign: "center",
    marginBottom: "30px",
    fontWeight: "500",
  },
  dialogButtons: {
    display: "flex",
    justifyContent: "center",
    gap: "15px",
  },
  cancelButton: {
    padding: "12px 24px",
    backgroundColor: "#F5F5F5",
    color: "#333",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    flex: "1",
  },
  confirmButton: {
    padding: "12px 24px",
    backgroundColor: "#2196F3",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 10px rgba(33, 150, 243, 0.3)",
    flex: "1",
  },
  loadingChat: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    fontSize: "18px",
    fontWeight: "500",
    color: "#555",
  },
};

export default styles; 