const styles = {
  container: {
    display: "flex", 
    padding: "20px",
    paddingLeft: "60px",
    paddingRight: "60px",
  },
  // 左側パネル（学習管理）
  leftPanel: {
    width: "280px",
    position: "fixed",
    top: "100px", 
    left: "60px",
    height: "auto",
    maxHeight: "calc(100vh - 180px)",
    overflowY: "auto",
    backgroundColor: "#fff",
    borderRadius: "20px",
    boxShadow: "0 5px 15px rgba(0,0,0,0.03)",
    border: "1px solid rgba(0, 0, 0, 0.04)",
  },
  studyInfoCard: {
    backgroundColor: "white",
    borderRadius: "16px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.08)",
    padding: "20px",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    maxHeight: "calc(100vh - 220px)", // 上下のパディングを考慮して調整
    overflowY: "auto",
  },
  statusIndicator: {
    display: "flex",
    alignItems: "center",
    marginBottom: "16px",
  },
  statusDot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    marginRight: "10px",
    transition: "all 0.3s ease",
  },
  statusText: {
    fontSize: "14px",
    fontWeight: "500",
    color: "#666",
    letterSpacing: "0.5px",
  },
  topicSection: {
    marginBottom: "20px",
  },
  topicTitle: {
    fontSize: "20px",
    fontWeight: "700",
    color: "#333",
    margin: "0 0 12px 0",
    lineHeight: "1.3",
  },
  motivationTag: {
    display: "inline-block",
    padding: "6px 12px",
    borderRadius: "18px",
    fontSize: "12px",
    fontWeight: "600",
  },
  timerContainer: {
    textAlign: "center",
    marginTop: "10px",
    marginBottom: "25px",
    padding: "0",
    display: "flex",
    justifyContent: "center",
  },
  timerCircle: {
    width: "180px",
    height: "180px",
    borderRadius: "50%",
    backgroundColor: "#f5f9ff",
    border: "2px solid #e6effd",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.05)",
    position: "relative",
  },
  timerValue: {
    fontSize: "28px",
    fontWeight: "500",
    color: "#333",
    fontFamily: "'Roboto Mono', monospace",
    letterSpacing: "1px",
    marginBottom: "6px",
  },
  controlsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    marginTop: "auto",
    marginBottom: "15px",
  },
  
  // 右側パネル（AIチャット用）
  rightPanel: {
    flex: 1,
    marginLeft: "300px",
    minHeight: "calc(100vh - 180px)",
  },
  
  // モーダルダイアログ
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    backdropFilter: "blur(3px)",
  },
  dialog: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "30px",
    width: "90%",
    maxWidth: "400px",
    boxShadow: "0 15px 35px rgba(0,0,0,0.2)",
  },
  dialogTitle: {
    margin: "0 0 20px 0",
    fontSize: "22px",
    color: "#333",
    textAlign: "center",
    fontWeight: "600",
  },
  dialogText: {
    fontSize: "15px",
    color: "#555",
    textAlign: "center",
    marginBottom: "30px",
    fontWeight: "500",
  },
  dialogButtons: {
    display: "flex",
    justifyContent: "center",
    gap: "15px",
  },
  cancelButton: {
    padding: "12px 24px",
    backgroundColor: "#F5F5F5",
    color: "#333",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    flex: "1",
  },
  confirmButton: {
    padding: "12px 24px",
    backgroundColor: "#2196F3",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 10px rgba(33, 150, 243, 0.3)",
    flex: "1",
  },
  loadingChat: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    fontSize: "18px",
    fontWeight: "500",
    color: "#555",
  },
};

export default styles; 